//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcStock.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MusteriTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MusteriTbl()
        {
            this.SatisTbl = new HashSet<SatisTbl>();
        }
    
        public int musteriID { get; set; }
        [Required(ErrorMessage ="Lütfen, Müsteri Adýný Giriniz")]
        [StringLength(50,ErrorMessage ="Max 50 Karakter Giriniz...")]
        public string musteriAd { get; set; }
        [Required(ErrorMessage = "Lütfen, Müsteri Soyadýný Giriniz")]
        [StringLength(50, ErrorMessage = "Max 50 Karakter Giriniz...")]
        public string musteriSoyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SatisTbl> SatisTbl { get; set; }
    }
}
