//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcStock.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatisTbl
    {
        public int satisID { get; set; }
        public Nullable<int> Urun { get; set; }
        public Nullable<int> musteri { get; set; }
        public Nullable<byte> adet { get; set; }
        public Nullable<decimal> fiyat { get; set; }
    
        public virtual MusteriTbl MusteriTbl { get; set; }
        public virtual TblUrunler TblUrunler { get; set; }
    }
}
